export const PERMISSIONS = {
  ADMIN_PROFILE_READ: 'admin.profile.read',
  ADMIN_PROFILE_UPDATE: 'admin.profile.update',
  ADMIN_SECURITY_UPDATE: 'admin.security.update',
  ADMIN_SETTINGS_READ: 'admin.settings.read',
  ADMIN_SETTINGS_UPDATE: 'admin.settings.update',

  EMPLOYEE_PROFILE_READ: 'people.employee.profile.read',
  EMPLOYEE_PROFILE_UPDATE: 'people.employee.profile.update',
  EMPLOYEE_DIRECTORY_READ: 'people.employee.directory.read',
  EMPLOYEE_DIRECTORY_CREATE: 'people.employee.directory.create',
  EMPLOYEE_DIRECTORY_UPDATE: 'people.employee.directory.update',
  EMPLOYEE_DIRECTORY_DELETE: 'people.employee.directory.delete',
  EMPLOYEE_DOCUMENTS_MANAGE: 'people.employee.documents.manage',
  ORG_UNIT_READ: 'people.org.unit.read',
  ORG_UNIT_MANAGE: 'people.org.unit.manage',

  ATTENDANCE_SELF_CHECKIN: 'attendance.time.self.checkin',
  ATTENDANCE_SELF_CHECKOUT: 'attendance.time.self.checkout',
  ATTENDANCE_SELF_RECESS: 'attendance.time.self.recess',
  ATTENDANCE_SELF_STATUS: 'attendance.time.self.status.read',
  ATTENDANCE_RECORDS_UPDATE: 'attendance.time.records.update',
  ATTENDANCE_SUMMARY_READ: 'attendance.time.summary.read',
  ATTENDANCE_ABSENCE_READ: 'attendance.time.absence.read',
  ATTENDANCE_SHIFT_MANAGE: 'attendance.time.shift.manage',
  ATTENDANCE_ROTA_MANAGE: 'attendance.time.rota.manage',
  ATTENDANCE_REGULARIZATION_CREATE: 'attendance.time.regularization.create',
  ATTENDANCE_REGULARIZATION_READ: 'attendance.time.regularization.read',
  ATTENDANCE_REGULARIZATION_APPROVE: 'attendance.time.regularization.approve',

  LEAVE_REQUEST_CREATE: 'leave.policy.request.create',
  LEAVE_SELF_READ: 'leave.policy.self.read',
  LEAVE_ALL_READ: 'leave.policy.all.read',
  LEAVE_APPROVAL_UPDATE: 'leave.policy.approval.update',
  LEAVE_DELETE: 'leave.policy.request.delete',
  LEAVE_POLICY_MANAGE: 'leave.policy.config.manage',
  LEAVE_BALANCE_READ: 'leave.policy.balance.read',
  LEAVE_BALANCE_MANAGE: 'leave.policy.balance.manage',
  LEAVE_ACCRUAL_RUN: 'leave.policy.accrual.run',
  LEAVE_ENCASHMENT_MANAGE: 'leave.policy.encashment.manage',

  HOLIDAY_CALENDAR_MANAGE: 'leave.policy.holiday.manage',
  HOLIDAY_CALENDAR_READ: 'leave.policy.holiday.read',
  HOLIDAY_SELECTION_MANAGE: 'leave.policy.holiday.selection.manage',
  HOLIDAY_EMPLOYEE_ROSTER_READ: 'leave.policy.holiday.employee.read',

  PAYROLL_SALARY_CREATE: 'payroll.compliance.salary.create',
  PAYROLL_SALARY_READ: 'payroll.compliance.salary.read',
  PAYROLL_SALARY_UPDATE: 'payroll.compliance.salary.update',
  PAYROLL_SALARY_DELETE: 'payroll.compliance.salary.delete',
  PAYROLL_EMPLOYEE_READ: 'payroll.compliance.employee.read',
  PAYROLL_PAYSLIP_GENERATE: 'payroll.compliance.payslip.generate',
  PAYROLL_PAYSLIP_EMAIL: 'payroll.compliance.payslip.email',
  PAYROLL_PAYSLIP_READ: 'payroll.compliance.payslip.read',
  PAYROLL_DEDUCTIONS_MANAGE: 'payroll.compliance.deductions.manage',
  PAYROLL_DEDUCTIONS_READ: 'payroll.compliance.deductions.read',
  PAYROLL_RUN_CREATE: 'payroll.compliance.run.create',
  PAYROLL_RUN_READ: 'payroll.compliance.run.read',
  PAYROLL_RUN_VALIDATE: 'payroll.compliance.run.validate',
  PAYROLL_RUN_LOCK: 'payroll.compliance.run.lock',
  PAYROLL_RUN_RELEASE: 'payroll.compliance.run.release',
  PAYROLL_RUN_OVERRIDE: 'payroll.compliance.run.override',
  PAYROLL_COMPLIANCE_VALIDATE: 'payroll.compliance.india.validate',
  PAYROLL_COMPLIANCE_EXPORT: 'payroll.compliance.india.export',

  DAILY_REPORT_SELF_CREATE: 'workflow.dailyReport.self.create',
  DAILY_REPORT_SELF_UPDATE: 'workflow.dailyReport.self.update',
  DAILY_REPORT_SELF_DELETE: 'workflow.dailyReport.self.delete',
  DAILY_REPORT_SELF_READ: 'workflow.dailyReport.self.read',
  DAILY_REPORT_TEAM_READ: 'workflow.dailyReport.team.read',
  DAILY_REPORT_TEAM_UPDATE: 'workflow.dailyReport.team.update',

  WORKFLOW_MANAGE: 'workflow.engine.manage',
  WORKFLOW_INSTANCE_READ: 'workflow.engine.instance.read',

  REPORTING_KPI_READ: 'reporting.executive.kpi.read',
  REPORTING_DRILLDOWN_READ: 'reporting.executive.drilldown.read',
  REPORTING_SCHEDULE_MANAGE: 'reporting.executive.schedule.manage',

  AUDIT_LOG_READ: 'security.audit.read',
  SECURITY_SESSION_READ: 'security.session.read',
  SECURITY_SESSION_REVOKE: 'security.session.revoke',
  SECURITY_MFA_MANAGE: 'security.mfa.manage',
  SECURITY_INTEGRATION_MANAGE: 'security.integration.manage',
  INTEGRATION_CONFIG_MANAGE: 'integrations.config.manage',
  INTEGRATION_NOTIFY_SEND: 'integrations.notify.send',
  INTEGRATION_ACCOUNTING_EXPORT: 'integrations.accounting.export',
  INTEGRATION_DEVICE_INGEST: 'integrations.device.ingest',
  OPERATIONS_JOB_READ: 'operations.job.read',
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
